### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-daniela932910#1]
Really cool job @daniela932910  !!!

Here you have some tips to improve the exercise:

- [x] Improve the meta title of the page
- [x] We need an h1 tag
- [x] Humanize text in `alt` attributes, a sentence without the underscore may do the trick.
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Try to avoid using tags names on classes
- [x] Fix the header to the viewport (you have a syntax error)
- [x] You have a vertical scroll, something is causing it, let's find it and fix it.
- [x] Nav links should be thinner.
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Let me know if you have any doubts ;)

Go for it!!

**Comment by ioanadamo** [comment]
@nasivuela I think I fixed everything; Could you please check and let me know if it´s all good?
Thank you in advance, Best regards

**Comment by nasivuela** [comment]
Good work @daniela932910. I have unchecked some points that still need to be improved and found some others:

- [x] Link to Adalab Logo on your folder instead that the one on 'https://raw.githubusercontent.com/'
- [x] Center the main title vertically
- [x] Remove extra CSS file
- [x] Improve hierarchy: add font-family to `body`

**Comment by ioanadamo** [comment]
@nasivuela i think i updated everything, i hope it's all good. Thank you.

**Comment by nasivuela** [comment]
Super @daniela932910 !!! You got it. Although, you still can improve the indentation on your CSS ;)

![](https://66.media.tumblr.com/98689f89a3d2d527727f2ab39852e5bd/tumblr_o7in72QD041v4yxmto1_400.gif)
